"""added img field in post tab;e

Revision ID: 968066c5f1a8
Revises: d0730a026576
Create Date: 2026-02-24 20:16:14.305552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968066c5f1a8'
down_revision: Union[str, Sequence[str], None] = 'd0730a026576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'posts', ['img_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'img_path')
    # ### end Alembic commands ###
