"""cascade delete on likes/comments when a post is removed

Revision ID: a1b2c3d4e5f6
Revises: 968066c5f1a8
Create Date: 2026-06-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '968066c5f1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Tables whose post_id foreign key should cascade when the parent post is deleted.
_CHILD_TABLES = ("likes", "comments")


def _drop_post_fk(table: str) -> None:
    """Drop whatever foreign key on ``table.post_id`` currently references posts.

    The constraint names were auto-generated by Postgres, so we look them up
    from the catalog rather than hardcoding a name that may differ per database.
    """
    op.execute(
        f"""
        DO $$
        DECLARE
            con_name text;
        BEGIN
            SELECT con.conname INTO con_name
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_class ref ON ref.oid = con.confrelid
            WHERE con.contype = 'f'
              AND rel.relname = '{table}'
              AND ref.relname = 'posts';
            IF con_name IS NOT NULL THEN
                EXECUTE format('ALTER TABLE {table} DROP CONSTRAINT %I', con_name);
            END IF;
        END $$;
        """
    )


def upgrade() -> None:
    """Recreate the post foreign keys with ON DELETE CASCADE."""
    for table in _CHILD_TABLES:
        _drop_post_fk(table)
        op.create_foreign_key(
            f"{table}_post_id_fkey",
            table,
            "posts",
            ["post_id"],
            ["id"],
            ondelete="CASCADE",
        )


def downgrade() -> None:
    """Restore the post foreign keys without cascade behaviour."""
    for table in _CHILD_TABLES:
        _drop_post_fk(table)
        op.create_foreign_key(
            f"{table}_post_id_fkey",
            table,
            "posts",
            ["post_id"],
            ["id"],
        )
